### PR TITLE
Add CD

### PR DESCRIPTION
**Pull request by vogdb**
@vogdb could you add travis-based deployment and some notes to the readme when you have the time?

Reference: https://github.com/cargomedia/guides/tree/master/software-projects

cc @tomaszdurka

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review and enable this project in travis. I don't have sufficient rights for that.

**Comment by njam** [comment]
done

**Comment by vogdb** [comment]
And the review too?

**Comment by njam** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
Well code looks good.

@njam for some reason I cannot see project settings here. Did you revoke my privs?

**Comment by njam** [comment]
Some permissions were changed when I migrated the Github permissions. Default is "write" now.
Maybe do another push to check the travis hook?

**Comment by tomaszdurka** [comment]
@vogdb please check, I cannot push (open-source, you need to add me as collaborator).

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
lgtm

**Pull request merged**
