### PR TITLE
Version 3.0.0

### PR DESCRIPTION
**Pull request by vogdb**
Tested and verified.

@njam FYI

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka all PR that you have recently been reviewing. Please confirm the merge.

**Comment by tomaszdurka** [comment]
Are covering the promise-based exiting in this version?

**Comment by tomaszdurka** [comment]
Otherwise looks good.

**Comment by vogdb** [comment]
> Are covering the promise-based exiting in this version?

Nope. Here exit functions are promise-based but when we exit we don't wait for them to resolve. I thought to implement it and release as a version `3.1.0`. In the current version, which we use on prod, we don't wait either.

**Comment by tomaszdurka** [comment]
Ok.

**Comment by vogdb** [comment]
I will merge it on Monday then. So, we have enough time for any unpredicted behaviour to fix.

**Pull request merged**
