### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
We log following events now: `['error', 'warning', 'connect', 'ready', 'reconnecting', 'end']`.

Example output of reconnection process on localhost:
```
$ bin/socket-redis.js
Starting worker `5251` to listen on port `8090`
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 end
down#1 reconnecting { delay: 255, attempt: 2 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 end
  up#2 reconnecting { delay: 255, attempt: 2 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 433, attempt: 3 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 433, attempt: 3 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 736, attempt: 4 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 736, attempt: 4 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 1251, attempt: 5 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 1251, attempt: 5 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 2126, attempt: 6 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 2126, attempt: 6 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 3614, attempt: 7 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 3614, attempt: 7 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 6143, attempt: 8 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 6143, attempt: 8 }
down#1 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
down#1 reconnecting { delay: 10443, attempt: 9 }
  up#2 error [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379]
  up#2 reconnecting { delay: 10443, attempt: 9 }
```

**Comment by tomaszdurka** [comment]
@njam wanna review?

**Comment by tomaszdurka** [comment]
@njam one more question, should I adjust it to Fluentd standards (encode json)?

**Comment by njam** [comment]
@vogdb could you review?

**Comment by vogdb** [comment]
I will try :)

**Comment by vogdb** [comment]
I don't see that we remove those listeners? Is it possible that we continue to receive events from previously opened redis clients?

**Comment by vogdb** [comment]
if not then lgtm

**Comment by tomaszdurka** [comment]
I don't think we ever consider to close that connections. We have reconnect mechanism which should keep them alive forever. So it's good.

**Comment by vogdb** [comment]
lgtm then. @njam there is still a question for you
> @njam one more question, should I adjust it to Fluentd standards (encode json)?

IMO we should do it if we use this tool on any prod.

**Comment by njam** [comment]
> should I adjust it to Fluentd standards (encode json)?

I think it's not so important. We only have this app installed on 1 server, and we check the logs rarely (if it doesn't work). So we can keep a normal log file for now, and even if we add fluentd a flat structure would be sufficient.

**Comment by tomaszdurka** [comment]
@vogdb could you release a new version?

**Comment by vogdb** [comment]
ok, I will try

**Pull request merged**
